table Walmart_Sales
	lineageTag: d7a4cb36-5fdb-4c1c-8924-bd7adfcd5099

	measure Min_date = min(Walmart_Sales[Date])
		formatString: General Date
		lineageTag: 63a0b633-a95d-4a3a-9607-1ee12850c083

	measure Max_Date = MAX(Walmart_Sales[Date])
		formatString: General Date
		lineageTag: 218eb4a2-3338-4612-8b8f-c638c0455b84

	measure Date_Range = "Data Collected from " & FORMAT([Min_date], "DD/MM/YYYY") & " To " & FORMAT([Max_Date], "DD/MM/YYYY")
		lineageTag: fdacfa89-e8d5-46b6-8ddb-1a43b213b5db

	measure Global_Average_Sales = AVERAGE(Walmart_Sales[Weekly_Sales])
		lineageTag: 8b8a8df0-e93c-4fca-b65f-4cb748304872

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Store Average Sales' = CALCULATE(AVERAGE(Walmart_Sales[Weekly_Sales]), ALLEXCEPT(Walmart_Sales, Walmart_Sales[Store]))
		lineageTag: 99b9d641-09f0-47f9-9b28-6de83bb11888

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Above Global Average' = IF(Walmart_Sales[Store Average Sales] > Walmart_Sales[Global_Average_Sales], 1, 0)
		formatString: 0
		lineageTag: bbbbc868-20f5-42cc-8862-a0b4982ff658

	column Store
		dataType: string
		lineageTag: f0509a3b-6fda-409e-8120-a98c0c66197d
		summarizeBy: none
		sourceColumn: Store

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 49b9e584-0274-4420-b3ef-6dc840a2d71c
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: b491c292-c579-4784-b97a-dbb512666e83
			defaultHierarchy: LocalDateTable_11cba466-aff8-48c8-bdd4-f79f32763485.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Weekly_Sales
		dataType: double
		lineageTag: 7dfe7d14-e260-4752-bcc2-462587eee176
		summarizeBy: sum
		sourceColumn: Weekly_Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Temperature
		dataType: double
		lineageTag: b64c4645-d798-4d30-a7b6-97976780fd4f
		summarizeBy: sum
		sourceColumn: Temperature

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fuel_Price
		dataType: double
		lineageTag: 7a338328-c144-4f7a-9033-955c379e6441
		summarizeBy: sum
		sourceColumn: Fuel_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPI
		dataType: double
		lineageTag: 67b639d5-4659-4558-a9cd-158696e8ed07
		summarizeBy: sum
		sourceColumn: CPI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unemployment
		dataType: double
		lineageTag: 29d376bc-68e1-4b82-a4cf-bfff1b4b5ae4
		summarizeBy: sum
		sourceColumn: Unemployment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Holiday = IF(WALMART_SALES[HOLIDAY_FLAG] = "1", "Holiday", "Non-Holiday")
		lineageTag: 7b833574-cc76-4853-8c83-e1d97bab3859
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Holiday_Flag
		dataType: string
		lineageTag: a2793ffb-d151-4b68-80bc-afa178566aa6
		summarizeBy: none
		sourceColumn: Holiday_Flag

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition Walmart_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data Analytics\Projects\Walmart Sales SQL\Walmart_Sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Store", Int64.Type}, {"Date", type date}, {"Weekly_Sales", type number}, {"Holiday_Flag", Int64.Type}, {"Temperature", type number}, {"Fuel_Price", type number}, {"CPI", type number}, {"Unemployment", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

